version: '3.6'

services:
  mysql: 
    image: mysql:8.0
    container_name: mysql
    restart: always
    ports: 
      - 3306:3306
    environment: 
      MYSQL_ROOT_HOST: localhost
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: echo_gorm
      MYSQL_USER: user
      MYSQL_PASSWORD: user
    volumes: 
    - ./database/mysql:/var/lib/mysql
    - ./database/migrations:/docker-entrypoint-initdb.d
  
  backend:
    image: golang:1.17
    container_name: backend
    volumes: 
      - ./:/go/src
    ports: 
      - 3000:3000
    depends_on:
      - mysql
    command: bash -c "cd /go/src && GOOS=linux go build main.go && go run main.go"

networks: 
  nt_mysql:
    driver: bridge
 